In [3]:
import numpy as np

In [9]:
import numpy as np
banking_data=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

customer_id=banking_data[:,0]
print(customer_id)

[101 102 103 104 105 106 107 108 109 110]


In [4]:
banking=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]
])



In [5]:




#[Customer_Id,Accoubt_balance,credit_score,Transaction_count,Years_Active]

banking=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]
])
print(banking)

[[   101  20000    775     25     10]
 [   102  25000    300     30     15]
 [   103  40000    400     15     20]
 [   104 400000    800    100     40]
 [   105 100000    900     50     21]
 [   106  90000    750    100      2]
 [   107   3000    301    100      5]
 [   108   1000    550     20      2]
 [   109  35000    600     30     10]
 [   110  80000    825     25      1]]


In [6]:
#Question 1: Array Creation and Manipulation
#Q1.1: Create a 4x4 identity matrix using np.eye()
banking=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]
])
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [166]:
#Q1.2: Create an array of 8 zeros using np.zeros()
identity_matrix= np.zeros(8)
print(identity_matrix)


[0. 0. 0. 0. 0. 0. 0. 0.]


In [167]:
#Q1.3: Create an array of 6 ones using np.ones()
array=np.ones(6)
print(array)


[1. 1. 1. 1. 1. 1.]


In [168]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
range_array=np.arange(16)
print(range_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [169]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linespace_array=np.linspace(0,100,8)
print(linespace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [7]:
import numpy as np
# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION
#Q2.1: What is the shape of the banking_data array?
banking_data=np.array([
 [101 , 20000 ,   775  ,   25 ,    10],
 [   102,  25000,   300,     30,     15],
 [   103 , 40000,   400,     15,     20],
 [   104, 400000,    800,    100,     40],
 [   105, 100000,    900,     50,    21],
 [   106, 90000,   750,    100,      2],
 [   107,   3000,    301,    100,      5],
 [   108,   1000,    550,     20,      2],
 [   109,  35000,    600 ,    30,     10],
 [   110,  80000 ,   825,     25,      1]
 ])
print(banking_data.shape)



(10, 5)


In [171]:
#Q2.2: What is the data type of the banking_data array?
banking_data=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]
])
print(banking_data.dtype)


int64


In [172]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
banking_data_size=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
print(banking_data_size.size)

50


In [173]:
#Q2.4: What is the number of dimensions of the banking_data array?
banking_data=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
print(banking_data.ndim)


2


In [174]:
#Q2.5: What is the memory size of the banking_data array in bytes?
banking_data=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
print(banking_data.nbytes)

400


In [175]:
# QUESTION 3: INDEXING AND SLICING

#Q3.1: Extract the first row of banking_data
banking_data=np.array([
    [101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
first_row=banking_data[0]
print(first_row)

[  101 20000   775    25    10]


In [176]:
#Q3.2: Extract the last row of banking_data
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
last_row=banking_data[-1]
print(last_row)

[  110 80000   825    25     1]


In [177]:
#Q3.3: Extract the Account_Balance column (column index 1)
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
account_balance=banking_data[:,1]
print(account_balance)


[ 20000  25000  40000 400000 100000  90000   3000   1000  35000  80000]


In [178]:
#Q3.4: Extract the first 4 rows and first 3 columns
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
x=banking_data[:4,:3]
print(x)

[[   101  20000    775]
 [   102  25000    300]
 [   103  40000    400]
 [   104 400000    800]]


In [179]:
#Q3.5: Extract rows 3 to 7 (inclusive)
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
rows=banking_data[3:8]
print(rows)


[[   104 400000    800    100     40]
 [   105 100000    900     50     21]
 [   106  90000    750    100      2]
 [   107   3000    301    100      5]
 [   108   1000    550     20      2]]


In [180]:
#Question 4: Mathematical Operations
#Q4.1: Calculate the sum of all account balances
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
sum=np.sum(banking_data[:,1])
print(sum)

794000


In [181]:
#Q4.2: Calculate the mean account balance
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
mean=np.mean(banking_data[:,1])
print(mean)

79400.0


In [182]:
#Q4.3: Calculate the standard deviation of account balances
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
std_dev=np.std(banking_data[:,1])
print(std_dev)

111944.80782957288


In [183]:
#Q4.4: Calculate the variance of account balances
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
variance_account_price=np.var(banking_data[:,1])
print(f"variance account price of banking account:",variance_account_price)

variance account price of banking account: 12531640000.0


In [184]:
#Q4.5: Calculate the median account balance
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

median_price=np.median(banking_data[:,1])
print(median_price)

37500.0


In [185]:
#Question 5: Statistical Functions
#Q5.1: Find the minimum and maximum account balances
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
min_account_price=np.min(banking_data[:,1])
max_account_price=np.max(banking_data[:,1])
print(min_account_price)
print(max_account_price)

1000
400000


In [186]:
#Q5.2: Find the minimum and maximum credit scores
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
min_credit_score=np.min(banking_data[:,2])
max_credit_score=np.max(banking_data[:,2])
print(min_credit_score)
print(max_credit_score)


300
900


In [10]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
percentile_account_bal=np.percentile(banking_data[:,1],[25,50,75])
print("25% percentile account balance:",percentile_account_bal[0])
print("50% percentile account balance:",percentile_account_bal[1])
print("75% percentile account balance:",percentile_account_bal[2])

25% percentile account balance: 21250.0
50% percentile account balance: 37500.0
75% percentile account balance: 87500.0


In [188]:
#Q5.4: Calculate the correlation between account balance and credit score
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
correlation=np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1]
print("correlation of account balance and credit score:", correlation)


correlation of account balance and credit score: 0.4732902330794412


In [189]:
#Q5.5: Calculate the covariance between account balance and credit score
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

covariance=np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print("covariance of account balance and credit score are:", covariance )

covariance of account balance and credit score are: 12510400.0


In [190]:
#Question 6: Array Reshaping and Manipulation
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
reshape=banking_data.reshape(5,10)
print(reshape)

[[   101  20000    775     25     10    102  25000    300     30     15]
 [   103  40000    400     15     20    104 400000    800    100     40]
 [   105 100000    900     50     21    106  90000    750    100      2]
 [   107   3000    301    100      5    108   1000    550     20      2]
 [   109  35000    600     30     10    110  80000    825     25      1]]


In [191]:
#Q6.2: Flatten the banking_data to a 1D array
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
flat=banking_data.flatten()
print(flat)


[   101  20000    775     25     10    102  25000    300     30     15
    103  40000    400     15     20    104 400000    800    100     40
    105 100000    900     50     21    106  90000    750    100      2
    107   3000    301    100      5    108   1000    550     20      2
    109  35000    600     30     10    110  80000    825     25      1]


In [192]:
#Q6.3: Transpose the banking_data
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
transpose=banking_data.T
print(transpose)

[[   101    102    103    104    105    106    107    108    109    110]
 [ 20000  25000  40000 400000 100000  90000   3000   1000  35000  80000]
 [   775    300    400    800    900    750    301    550    600    825]
 [    25     30     15    100     50    100    100     20     30     25]
 [    10     15     20     40     21      2      5      2     10      1]]


In [193]:
#Q6.4: Split the banking_data into 2 equal parts vertically
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

split_bankingdata=np.vsplit(banking_data,2)
print("1st part")
print(split_bankingdata[0])
print("2nd part")
print(split_bankingdata[1])


1st part
[[   101  20000    775     25     10]
 [   102  25000    300     30     15]
 [   103  40000    400     15     20]
 [   104 400000    800    100     40]
 [   105 100000    900     50     21]]
2nd part
[[  106 90000   750   100     2]
 [  107  3000   301   100     5]
 [  108  1000   550    20     2]
 [  109 35000   600    30    10]
 [  110 80000   825    25     1]]


In [194]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

split_horizontally=np.hsplit(banking_data,5)
print("1st part")
print(split_horizontally[0])
print("2nd part")
print(split_horizontally[1])

1st part
[[101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]
 [109]
 [110]]
2nd part
[[ 20000]
 [ 25000]
 [ 40000]
 [400000]
 [100000]
 [ 90000]
 [  3000]
 [  1000]
 [ 35000]
 [ 80000]]


In [195]:
#Question 7: Logical Operations and Filtering
#Q7.1: Find customers with account balance greater than $100,000
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

acc_bal=banking_data[banking_data[:,1]>=100000]
print("Total account balance more then $100000 are:", acc_bal)

Total account balance more then $100000 are: [[   104 400000    800    100     40]
 [   105 100000    900     50     21]]


In [196]:
#Q7.2: Find customers with credit score greater than 800
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
credit_score=banking_data[banking_data[:,2]>=800]
print(credit_score)

[[   104 400000    800    100     40]
 [   105 100000    900     50     21]
 [   110  80000    825     25      1]]


In [197]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
Transaction=banking_data[banking_data[:,3]>50]
credit_score=banking_data[banking_data[:,2]<750]
print("Transaction more then  50 are:", Transaction)
print("credit score less then 750 are:", credit_score)

Transaction more then  50 are: [[   104 400000    800    100     40]
 [   106  90000    750    100      2]
 [   107   3000    301    100      5]]
credit score less then 750 are: [[  102 25000   300    30    15]
 [  103 40000   400    15    20]
 [  107  3000   301   100     5]
 [  108  1000   550    20     2]
 [  109 35000   600    30    10]]


In [198]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
count=0
for row in banking_data:
    balance=row[1]
if 10000<= balance <=100000:
    count += 1
    print("customers have account balance between 10000 to 1000000 are:",count)

customers have account balance between 10000 to 1000000 are: 1


In [199]:
#Q7.5: Find the index of the customer with the highest credit score
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])

customer_index=np.argmax(banking_data[:,2])
print("customer with high credit score is:", customer_index)
print("customer id is:", banking_data[customer_index,0])

customer with high credit score is: 4
customer id is: 105


In [200]:
#Question 8: Sorting and Searching
#Q8.1: Sort the banking_data by account balance (ascending)
banking_data=np.array([[101,20000,775,25,10],
    [102,25000,300,30,15],
    [103,40000,400,15,20],
    [104,400000,800,100,40],
    [105,100000,900,50,21],
    [106,90000,750,100,2],
    [107,3000,301,100,5],
    [108,1000,550,20,2],
    [109,35000,600,30,10],
    [110,80000,825,25,1]])
sorting=banking_data[banking_data[:,1].argsort()]
print(sorting)


[[   108   1000    550     20      2]
 [   107   3000    301    100      5]
 [   101  20000    775     25     10]
 [   102  25000    300     30     15]
 [   109  35000    600     30     10]
 [   103  40000    400     15     20]
 [   110  80000    825     25      1]
 [   106  90000    750    100      2]
 [   105 100000    900     50     21]
 [   104 400000    800    100     40]]


In [201]:
#Q8.2: Sort the banking_data by credit score (descending)
from bank_data import banking_data
descending=banking_data[banking_data[:,3].argsort()]
print(descending)





[[   103  40000    400     15     20]
 [   108   1000    550     20      2]
 [   101  20000    775     25     10]
 [   110  80000    825     25      1]
 [   109  35000    600     30     10]
 [   102  25000    300     30     15]
 [   105 100000    900     50     21]
 [   106  90000    750    100      2]
 [   104 400000    800    100     40]
 [   107   3000    301    100      5]]


In [202]:

#Q8.3: Find the indices that would sort the array by years active
from bank_data import banking_data
indices=np.argsort(banking_data[:,4])
print("The indices that would sort the array by years active are:", indices )

The indices that would sort the array by years active are: [4 1 2 5 6 3 0 9 8 7]


In [203]:
#Q8.4: Find the customer with the second highest account balance
from bank_data import banking_data
account_balance=np.argsort(banking_data[:,1])[-2]
customer=banking_data[account_balance]
print(account_balance)
print(customer)

8
[   105 100000    900     50     21]


In [204]:
# Q8.5: Find the customer with the lowest transaction count
from bank_data import banking_data
lowest_balance=np.argmin(banking_data[:,2])
customer=banking_data[lowest_balance]
print("Lowest account balance is:",lowest_balance)
print("customer data is:", customer)

Lowest account balance is: 0
customer data is: [  102 25000   300    30    15]


In [205]:
#Question 9: Mathematical Functions
#Q9.1: Calculate the absolute values of all elements
from bank_data import banking_data
print(np.abs(banking_data))


[[   102  25000    300     30     15]
 [   106  90000    750    100      2]
 [   108   1000    550     20      2]
 [   109  35000    600     30     10]
 [   110  80000    825     25      1]
 [   107   3000    301    100      5]
 [   101  20000    775     25     10]
 [   104 400000    800    100     40]
 [   105 100000    900     50     21]
 [   103  40000    400     15     20]]


In [206]:
#Q9.2: Calculate the square root of all account balances
from bank_data import banking_data
print(np.sqrt(banking_data[:,1]))


[158.11388301 300.          31.6227766  187.08286934 282.84271247
  54.77225575 141.42135624 632.45553203 316.22776602 200.        ]


In [207]:
#Q9.3: Calculate the square of all credit scores
from bank_data import banking_data
print(np.square(banking_data[:,2]))


[ 90000 562500 302500 360000 680625  90601 600625 640000 810000 160000]


In [208]:
#Q9.4: Calculate the exponential of all transaction counts
from bank_data import banking_data
print(np.exp(banking_data[:,3]))


[1.06864746e+13 2.68811714e+43 4.85165195e+08 1.06864746e+13
 7.20048993e+10 2.68811714e+43 7.20048993e+10 2.68811714e+43
 5.18470553e+21 3.26901737e+06]


In [209]:
#Q9.5: Calculate the natural logarithm of all account balances
from bank_data import banking_data
print(np.log(banking_data[:,1]))


[10.1266311  11.40756495  6.90775528 10.46310334 11.28978191  8.00636757
  9.90348755 12.89921983 11.51292546 10.59663473]


In [210]:
#Question 10: Advanced Operations
#Q10.1: Calculate the cumulative sum of account balances
from bank_data import banking_data
print(np.cumsum(banking_data[:,1]))


[ 25000 115000 116000 151000 231000 234000 254000 654000 754000 794000]


In [211]:
#Q10.2: Calculate the cumulative product of transaction counts
from bank_data import banking_data
print(np.cumprod(banking_data[:,3]))


[              30             3000            60000          1800000
         45000000       4500000000     112500000000   11250000000000
  562500000000000 8437500000000000]


In [212]:
#Q10.3: Calculate the difference between consecutive account balances
from bank_data import banking_data
print(np.diff(banking_data[:,1]))

[  65000  -89000   34000   45000  -77000   17000  380000 -300000  -60000]


In [213]:
#Q10.4: Calculate the gradient of account balances
from bank_data import banking_data
print(np.gradient(banking_data[:,1]))


[  65000.  -12000.  -27500.   39500.  -16000.  -30000.  198500.   40000.
 -180000.  -60000.]


In [214]:
#Q10.5: Calculate the histogram of account balances with 5 bins
from bank_data import banking_data
print(np.histogram(banking_data[:,1], bins=5))

(array([7, 2, 0, 0, 1]), array([  1000.,  80800., 160600., 240400., 320200., 400000.]))


In [215]:
#Question 11: Random Numbers and Simulation
#Q11.1: Generate 6 random integers between 1 and 1000
from bank_data import banking_data
print(np.random.randint(1,1000,6))


[596 107 124 570 215 738]


In [216]:
#Q11.2: Generate 6 random floats between 0 and 1
from bank_data import banking_data
print(np.random.random(6))

[0.68482974 0.4809319  0.39211752 0.34317802 0.72904971 0.43857224]


In [217]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

print(np.random.normal(700,100,6))


[685.66275259 638.08090993 623.05665285 757.67460214 712.65259202
 569.85110255]


In [218]:
#Q11.4: Shuffle the banking_data rows randomly
from bank_data import banking_data
shuffle=banking_data.copy()
np.random.shuffle(shuffle)
print(shuffle)


[[   104 400000    800    100     40]
 [   108   1000    550     20      2]
 [   103  40000    400     15     20]
 [   101  20000    775     25     10]
 [   109  35000    600     30     10]
 [   106  90000    750    100      2]
 [   102  25000    300     30     15]
 [   107   3000    301    100      5]
 [   105 100000    900     50     21]
 [   110  80000    825     25      1]]


In [219]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
from bank_data import banking_data
np.random.seed(123)
set_random_seed=np.random.random(4)
print(set_random_seed)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [220]:
#Question 12: Linear Algebra Operations
#Q12.1: Calculate the dot product of account balance and credit score columns
from bank_data import banking_data
dot_product=np.dot(banking_data[:,1], banking_data[:,2])
print("account balane of dot product:", dot_product)


account balane of dot product: 604953000


In [221]:
#Q12.2: Calculate the cross product of first two rows
from bank_data import banking_data
cross_prod=np.cross(banking_data[0,:3], banking_data[1,:3])
print(cross_prod)

[-8250000   -44700  6530000]


In [222]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
from bank_data import banking_data
print(np.linalg.norm(banking_data[:,1]))


434004.6082704653


In [223]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
from bank_data import banking_data
matrix_3x3=np.array([[0,2,4],[1,3,5],[7,8,9]])
matrix_3x3_deter=np.linalg.det(matrix_3x3)
print(matrix_3x3)
print(matrix_3x3_deter)

[[0 2 4]
 [1 3 5]
 [7 8 9]]
0.0


In [3]:
#Q12.5: Calculate the inverse of the 3x3 matrix
invert_matrix_3x3=np.array([[3,2,4],
                            [1,3,5],
                            [7,8,9]])
print(invert_matrix_3x3)
invert_matrix=np.linalg.inv(invert_matrix_3x3)

print(invert_matrix.astype(int))

[[3 2 4]
 [1 3 5]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [244]:
#Question 13: String Operations
#Q13.1: Convert all customer IDs to strings
from bank_data import banking_data
customer_id_string = banking_data[:, 0].astype(str)
print(customer_id_string)


['102' '106' '108' '109' '110' '107' '101' '104' '105' '103']


In [246]:
#Q13.2: Check if any customer ID contains '100'
from bank_data import banking_data
customer_id_contains= np.char.find(customer_id_string,'100')>=0
print(customer_id_contains)

[False False False False False False False False False False]


In [247]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
from bank_data import banking_data
customer_id_upper=np.char.upper(customer_id_string)
print(customer_id_upper)

['102' '106' '108' '109' '110' '107' '101' '104' '105' '103']


In [249]:
#Q13.4: Count the length of each customer ID string
from bank_data import banking_data
customer_id_len=np.char.str_len(customer_id_string)
print(customer_id_len)

[3 3 3 3 3 3 3 3 3 3]


In [250]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
from bank_data import banking_data
replace_id=np.char.replace(customer_id_string,'100','CUST')
print(replace_id)

['102' '106' '108' '109' '110' '107' '101' '104' '105' '103']


In [251]:
#Question 14: Date and Time Operations
#Q14.1: Convert years active to months
from bank_data import banking_data
years_to_month=banking_data[:,4]*12
print(years_to_month)


[180  24  24 120  12  60 120 480 252 240]


In [11]:
#Q14.2: Calculate the average years active
from bank_data import banking_data
active_avg_years=np.mean(banking_data[:,4])
print(active_avg_years)

12.6


In [253]:
#Q14.3: Find customers who have been active for more than 5 years
from bank_data import banking_data
Active_cust_for_5yrs=banking_data[banking_data[:,4]>5]
print(Active_cust_for_5yrs)

[[   102  25000    300     30     15]
 [   109  35000    600     30     10]
 [   101  20000    775     25     10]
 [   104 400000    800    100     40]
 [   105 100000    900     50     21]
 [   103  40000    400     15     20]]


In [254]:
#Q14.4: Calculate the total time all customers have been active (in years)
from bank_data import banking_data
Active_cust=np.sum(banking_data[:,4])
print(Active_cust)

126


In [12]:
#Q14.5: Find the customer with the shortest time active
from bank_data import banking_data
shorter_time_cust=np.min(banking_data[:,4])
print(shorter_time_cust)
shorter_time=banking_data[shorter_time_cust]
print(shorter_time)

1
[  102 25000   300    30    15]


In [263]:
#Question 15: Advanced Array Operations
#Q15.1: Apply a function to calculate 5% interest on all account balances
from bank_data import banking_data
interest_on_acc_bal=banking_data[:,1]*0.05
print(interest_on_acc_bal)
account_balance_after_interest=banking_data[:,1]+interest_on_acc_bal
print(account_balance_after_interest)

[ 1250.  4500.    50.  1750.  4000.   150.  1000. 20000.  5000.  2000.]
[ 26250.  94500.   1050.  36750.  84000.   3150.  21000. 420000. 105000.
  42000.]


In [268]:
#Q15.2: Use np.where to categorize customers by balance ranges
from bank_data import banking_data
acc_bal=banking_data[:,1]
category=np.where(acc_bal<20000,'low balance',np.where(acc_bal<=100000,'medium balance','high balance'))
customer_balances=np.column_stack((banking_data[:,0],acc_bal,category))
print(customer_balances)



[['102' '25000' 'medium balance']
 ['106' '90000' 'medium balance']
 ['108' '1000' 'low balance']
 ['109' '35000' 'medium balance']
 ['110' '80000' 'medium balance']
 ['107' '3000' 'low balance']
 ['101' '20000' 'medium balance']
 ['104' '400000' 'high balance']
 ['105' '100000' 'medium balance']
 ['103' '40000' 'medium balance']]


In [270]:
#Q15.3: Use np.select to categorize customers by credit score ranges
from bank_data import banking_data
credit_card_range=[banking_data[:,2]<300,
(banking_data[:,2]>=600)&(banking_data[:,2]<900),
banking_data[:,2]>=900]
criteria=["loans not given","loans given with more interest","loans given with less interest"]
category_customers=np.select(credit_card_range,criteria,default='not eligible')
print(category_customers)



['not eligible' 'loans given with more interest' 'not eligible'
 'loans given with more interest' 'loans given with more interest'
 'not eligible' 'loans given with more interest'
 'loans given with more interest' 'loans given with less interest'
 'not eligible']


In [282]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
from bank_data import banking_data
Acc_balances=banking_data[:,1]
interest_rates=np.piecewise(Acc_balances,[Acc_balances<=20000,(Acc_balances>20000)& (Acc_balances<100000),Acc_balances>=400000],[0.05,0.07,0.10])
Account_interest=np.column_stack((banking_data[:,0],Acc_balances,interest_rates))
print(Account_interest)

[[   102  25000      0]
 [   106  90000      0]
 [   108   1000      0]
 [   109  35000      0]
 [   110  80000      0]
 [   107   3000      0]
 [   101  20000      0]
 [   104 400000      0]
 [   105 100000      0]
 [   103  40000      0]]


In [283]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
from bank_data import banking_data
sum_row=np.apply_along_axis(np.sum,1,banking_data)
print(sum_row)


[ 25447  90958   1680  35749  80961   3513  20911 401044 101076  40538]


In [5]:
#Question 16: Array Concatenation and Stacking
#Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np
A1=np.array([1,3,5])
A2=np.array([2,4,6])
hstacked=np.hstack([A1,A2])
print("horrizontally array:",A1)
print("horrizontally array:",A2)
print("horrizontally hstack:",hstacked)

horrizontally array: [1 3 5]
horrizontally array: [2 4 6]
horrizontally hstack: [1 3 5 2 4 6]


In [16]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
import numpy as np
A1=np.array([1,3,5])
A2=np.array([2,4,6])
vstacked=np.vstack([A1,A2])
print(f"vertically stacked:{vstacked}")

vertically stacked:[[1 3 5]
 [2 4 6]]


In [10]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()

concat=np.concatenate([A1,A2])
print("concatenated along axis :",concat)

concatenated along axis : [1 3 5 2 4 6]


In [11]:
#Q16.4: Stack arrays depth-wise using np.dstack()
dstacked=np.dstack([A1,A2])
print("array depth wise:",dstacked)

array depth wise: [[[1 2]
  [3 4]
  [5 6]]]


In [12]:
#Q16.5: Create a column stack using np.column_stack()
column_stack=np.column_stack([A1,A2])
print(column_stack)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
#Question 17: Array Splitting Operations
#Q17.1: Split an array into 3 equal parts using np.split()
a1_to_split=np.array([ 101,20000,775,25,10,2,5,9,1])
split=np.split(a1_to_split,3)
print("original array:",a1_to_split)
for i, part in enumerate(split):
    print(f"part{i+1}:{part}")



original array: [  101 20000   775    25    10     2     5     9     1]
part1:[  101 20000   775]
part2:[25 10  2]
part3:[5 9 1]


In [24]:
#Q17.2: Split an array at specific indices using np.split()
split=np.split(a1_to_split,[3,6])
print("split[3,6]:")
for i, part in enumerate(split):
    print("part{i+1}:{part}")


split[3,6]:
part{i+1}:{part}
part{i+1}:{part}
part{i+1}:{part}


In [25]:
#Q17.3: Split an array horizontally using np.hsplit()
arr_2d=np.array([[2,4,6],[1,2,3]])
hsplit_parts=np.hsplit(arr_2d,3)
print(f"original 2D array:{arr_2d}")
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part {i+1}:{part}")


original 2D array:[[2 4 6]
 [1 2 3]]
Horizontal part 1:[[2]
 [1]]
Horizontal part 2:[[4]
 [2]]
Horizontal part 3:[[6]
 [3]]


In [28]:
#Q17.4: Split an array vertically using np.vsplit()
arr_2d=np.array([[2,4,6],[1,2,3]])
vsplit_parts=np.vsplit(arr_2d,2)
print(vsplit_parts)



[array([[2, 4, 6]]), array([[1, 2, 3]])]


In [29]:
#Q17.5: Split an array into equal chunks using np.array_split()
arr_2d=np.array([[2,4,6],[1,2,3]])
chunks=np.array_split(arr_2d,4)
print(chunks)

[array([[2, 4, 6]]), array([[1, 2, 3]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [33]:
#Question 18: Array Repetition and Tiling
#Q18.1: Repeat each element of an array 3 times using np.repeat()
arr1=([1,2],[3,4],[5,6])
repeat1=np.repeat(arr1,3)
print(repeat1)



[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


In [34]:
#Q18.2: Repeat an entire array 2 times using np.tile()
arr1=([1,2],[3,4],[5,6])
tiled_arr=np.tile(arr1,2)
print(tiled_arr)

[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]


In [36]:
#Q18.3: Repeat a 2D array using np.tile()
arr_2d=np.array([[2,4,6],[1,2,3]])
tile_2d_arr=np.tile(arr_2d,(2,2))
print(tile_2d_arr)



[[2 4 6 2 4 6]
 [1 2 3 1 2 3]
 [2 4 6 2 4 6]
 [1 2 3 1 2 3]]


In [ ]:
#Q18.4: Create a pattern using np.tile()

pattern=np.array([1,0])
pattern_tiled=np.tile(pattern, 5)
print(pattern)
print(pattern_tiled)


[1 0]
[1 0 1 0 1 0 1 0 1 0]


In [48]:
#Q18.5: Repeat elements with different counts using np.repeat()
arr1=np.arange(1,6)
repeat_count=[1,2,3,4,5]
repeated_arr=np.repeat(arr1, repeat_count)
print(arr1)
print("repeat_count:", repeat_count)
print("repeated_var:", repeated_arr)


[1 2 3 4 5]
repeat_count: [1, 2, 3, 4, 5]
repeated_var: [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5]


In [51]:
#Question 19: Array Comparison and Logical Operations
#Q19.1: Compare two arrays for equality using np.array_equal()

arr1=np.array([2,4,6])
arr2=np.array([2,4,6])
arr3=np.array([1,2,6])
print("arr1:",arr1)
print("arr2:",arr2)
print("arr3:",arr3)
arr1_eql_arr2=(np.array_equal(arr1,arr2))
print(arr1_eql_arr2)
arr1_eql_arr3=(np.array_equal(arr1,arr3))
print(arr1_eql_arr3)

arr1: [2 4 6]
arr2: [2 4 6]
arr3: [1 2 6]
True
False


In [53]:
#Q19.2: Check if arrays are close using np.allclose()
close_arr=np.allclose(arr1,arr3)
print(close_arr)


False


In [55]:
#Q19.3: Apply logical AND operation between arrays

log_arr=np.logical_and(arr1,arr2)
print(log_arr)

[ True  True  True]


In [56]:
#Q19.4: Apply logical OR operation between arrays
log_arr=np.logical_or(arr1,arr2)
print(log_arr)


[ True  True  True]


In [58]:
#Q19.5: Apply logical NOT operation to an array
log_arr=np.logical_not(arr2,arr3)
print(log_arr)


[1 1 1]


In [59]:
#Question 20: Array Set Operations
#Q20.1: Find unique elements in an array using np.unique()
arr_duplicate=np.array([1,2,2,3,4,5,5,6,6])
unique_ele=np.unique(arr_duplicate)
print(arr_duplicate)
print(unique_ele)

[1 2 2 3 4 5 5 6 6]
[1 2 3 4 5 6]


In [61]:
#20.2: Find the intersection of two arrays using np.intersect1d()
arr1=np.array([2,4,6,8])
arr2=np.array([1,3,5,8])
intersection=np.intersect1d(arr1,arr2)
print(intersection)


[8]


In [62]:
#Q20.3: Find the union of two arrays using np.union1d()

union=np.union1d(arr1,arr2)
print(union)

[1 2 3 4 5 6 8]


In [63]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
set_diff=np.setdiff1d(arr1,arr2)
print(set_diff)


[2 4 6]


In [64]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
symmetric_diff=np.setxor1d(arr1,arr2)
print(symmetric_diff)

[1 2 3 4 5 6]
